### ISSUE TITLE
首页背景要怎么改

### ISSUE THREAD

**Issue by xulouzhe** [trinitrotofu/Bubble#1]

**Comment by trinitrotofu** [comment]
暂时不支持修改首页背景，但该功能已经在计划之中，后续版本将实现该功能，也欢迎您提供更多改进意见，谢谢！

另：如果您有一定编程能力，您可以通过设定自定义 css 实现该功能，即在 typecho 后台修改 style.css。大概就是修改`.section-shaped .shape-style-1.shape-primary`的`background-image`属性。

**Comment by trinitrotofu** [comment]
@xulouzhe 考虑到下一个版本更新可能仍然不会添加自定义头图功能，所以为您写了一份自定义 css，您只需要打开 typecho 后台->控制台->外观->编辑当前外观->style.css，在编辑框中加入以下代码即可自定义首页头图。

```css
.section-shaped .shape-style-1.shape-primary {
	background-image: url('这里换成你的头图地址');
	background-position: center;
	background-repeat: no-repeat;
	background-attachment: fixed;
	background-size: cover;
}
```
